// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Priyanshu Rai"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/change-password/{id}": {
            "put": {
                "description": "change admin Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Change user Password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Change password of user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userAuth.ChangeUserPasswordReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userAuth.ChangeUserPasswordResDto"
                        }
                    }
                }
            }
        },
        "/user/create-log-entry": {
            "post": {
                "description": "CreateLogEntry",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logEntry"
                ],
                "summary": "CreateLogEntry",
                "parameters": [
                    {
                        "description": "CreateLogEntry for user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/logEntry.LogEntryReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/logEntry.GetLogEntryResDto"
                        }
                    }
                }
            }
        },
        "/user/edit-appointment/{id}": {
            "put": {
                "description": "Update appointment",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logEntry"
                ],
                "summary": "Update appointment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "appointment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "alert",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "notes",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "whatItIsFor",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "when",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/logEntry.GetAppointmentResDto"
                        }
                    }
                }
            }
        },
        "/user/fetch-all-data": {
            "get": {
                "description": "fetch all required data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logEntry"
                ],
                "summary": "fetch all required data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/logEntry.CatgoriesResDto"
                        }
                    }
                }
            }
        },
        "/user/forgot-password": {
            "post": {
                "description": "Forgot Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Forgot Password",
                "parameters": [
                    {
                        "description": "forgot password for user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userAuth.UserForgotPasswordReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userAuth.UserPasswordResDto"
                        }
                    }
                }
            }
        },
        "/user/get-info/{id}": {
            "get": {
                "description": "Fetch user By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Fetch user By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "business user ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userAuth.GetUserResDto"
                        }
                    }
                }
            }
        },
        "/user/get-misc-data": {
            "get": {
                "description": "Fetch All misc data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Fetch All misc data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userAuth.CatgoriesResDto"
                        }
                    }
                }
            }
        },
        "/user/logentry-info/{id}": {
            "get": {
                "description": "Fetch logentry By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logEntry"
                ],
                "summary": "Fetch logentry By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "logentry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/logEntry.LogentryResDto"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Login User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "Login User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userAuth.LoginReqDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/user/monthly-insights": {
            "get": {
                "description": "Retrieves mental health and physical health data for a specified month",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logEntry"
                ],
                "summary": "Fetch monthly insights data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Month and Year (MM-YYYY)",
                        "name": "monthYear",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/logEntry.InsightsResDto"
                        }
                    }
                }
            }
        },
        "/user/months": {
            "get": {
                "description": "Fetch log entry data for a specific month and year.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logEntry"
                ],
                "summary": "Fetch log entry data for a specific month and year.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Month (01-12)",
                        "name": "month",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Year (YYYY)",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully fetched log entry data",
                        "schema": {
                            "$ref": "#/definitions/logEntry.CatgoriesResDto"
                        }
                    },
                    "400": {
                        "description": "Invalid date format or missing parameters",
                        "schema": {
                            "$ref": "#/definitions/logEntry.CatgoriesResDto"
                        }
                    },
                    "500": {
                        "description": "Failed to fetch or process data",
                        "schema": {
                            "$ref": "#/definitions/logEntry.CatgoriesResDto"
                        }
                    }
                }
            }
        },
        "/user/resend-otp": {
            "post": {
                "description": "Resend 6 digit OTP to email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Resend OTP",
                "parameters": [
                    {
                        "description": "Resend 6 digit OTP to email",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userAuth.ResendOtpReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userAuth.UserPasswordResDto"
                        }
                    }
                }
            }
        },
        "/user/reset-password": {
            "put": {
                "description": "Reset user password after OTP verification using the new password and confirm password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Reset user Password after OTP Verification",
                "parameters": [
                    {
                        "description": "Reset user password after OTP verification",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userAuth.ResetPasswordAfterOtpReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userAuth.UserPasswordResDto"
                        }
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "description": "Signup user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Signup user",
                "parameters": [
                    {
                        "description": "send 6 digit otp to email for signup",
                        "name": "signup",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userAuth.SignupReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userAuth.SignupResDto"
                        }
                    }
                }
            }
        },
        "/user/update-user-data/{id}": {
            "put": {
                "description": "Update user",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication header",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userAuth.UpdateUserResDto"
                        }
                    }
                }
            }
        },
        "/user/verify-otp": {
            "post": {
                "description": "Verify the entered 6 digit OTP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Verify user OTP",
                "parameters": [
                    {
                        "description": "Verify 6 digit OTP",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userAuth.VerifyOtpReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userAuth.UserPasswordResDto"
                        }
                    }
                }
            }
        },
        "/user/verify-otp-for-signup": {
            "post": {
                "description": "Verify the entered 6 digit OTP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user authorization"
                ],
                "summary": "Verify OTP for signup",
                "parameters": [
                    {
                        "description": "Verify 6 digit OTP and insert data into database",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userAuth.VerifyOtpSignupReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userAuth.VerifyOtpSignupResDto"
                        }
                    }
                }
            }
        },
        "/user/weekly-insights": {
            "get": {
                "description": "Retrieves mental health and physical health data for a specified week",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logEntry"
                ],
                "summary": "Fetch weekly insights data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date of the week (YYYY-MM-DD)",
                        "name": "firstDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date of the week (YYYY-MM-DD)",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/logEntry.InsightsResDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "logEntry.CategoriesRes": {
            "type": "object",
            "properties": {
                "alert": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "feel": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "painLevel": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "ways": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "whatItIsFor": {
                    "type": "string"
                },
                "when": {
                    "type": "string"
                }
            }
        },
        "logEntry.CatgoriesResDto": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/logEntry.CategoriesRes"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "logEntry.GetAppointmentResDto": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "logEntry.GetLogEntryResDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "logEntry.InsightsData": {
            "type": "object",
            "properties": {
                "mentalHealth": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/logEntry.MentalHealthRes"
                    }
                },
                "physicalHealth": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/logEntry.PhysicalHealthRes"
                    }
                }
            }
        },
        "logEntry.InsightsResDto": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/logEntry.InsightsData"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "logEntry.LogEntryReqDto": {
            "type": "object",
            "properties": {
                "alert": {
                    "type": "string"
                },
                "dateTime": {
                    "type": "string"
                },
                "feel": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "painLevel": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "ways": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "whatItIsFor": {
                    "type": "string"
                }
            }
        },
        "logEntry.LogentryRes": {
            "type": "object",
            "properties": {
                "alert": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "feel": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                },
                "painLevel": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "ways": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "whatItIsFor": {
                    "type": "string"
                },
                "when": {
                    "type": "string"
                }
            }
        },
        "logEntry.LogentryResDto": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/logEntry.LogentryRes"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "logEntry.MentalHealthRes": {
            "type": "object",
            "properties": {
                "avgFeel": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "day": {
                    "type": "string"
                }
            }
        },
        "logEntry.PhysicalHealthRes": {
            "type": "object",
            "properties": {
                "avgPainLevel": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "day": {
                    "type": "string"
                }
            }
        },
        "userAuth.CategoriesRes": {
            "type": "object",
            "properties": {
                "mentalHealth": {
                    "$ref": "#/definitions/userAuth.MentalHealth"
                },
                "physicalHealth": {
                    "$ref": "#/definitions/userAuth.PhysicalHealth"
                }
            }
        },
        "userAuth.CatgoriesResDto": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/userAuth.CategoriesRes"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "userAuth.ChangeUserPasswordReqDto": {
            "type": "object",
            "properties": {
                "confirmPassword": {
                    "type": "string"
                },
                "currentPassword": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                }
            }
        },
        "userAuth.ChangeUserPasswordResDto": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "userAuth.GetUserResDto": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/userAuth.UserData"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "userAuth.LoginReqDto": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "userAuth.MentalHealth": {
            "type": "object",
            "properties": {
                "other": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "popular": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "userAuth.PhysicalHealth": {
            "type": "object",
            "properties": {
                "other": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "popular": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "userAuth.ResendOtpReqDto": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "userAuth.ResetPasswordAfterOtpReqDto": {
            "type": "object",
            "properties": {
                "confirmPassword": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                }
            }
        },
        "userAuth.SignupReqDto": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "userAuth.SignupResDto": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "userAuth.UpdateUserResDto": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "userAuth.UserData": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "userAuth.UserForgotPasswordReqDto": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "userAuth.UserPasswordResDto": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "userAuth.UserResDto": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "userAuth.VerifyOtpReqDto": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "otp": {
                    "type": "string"
                }
            }
        },
        "userAuth.VerifyOtpSignupReqDto": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "otp": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "userAuth.VerifyOtpSignupResDto": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/userAuth.UserResDto"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "nssdmvtpj2.us-east-1.awsapprunner.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Opsy Backend",
	Description:      "Opsy Backend Backend (in GoLang)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
